name: Lint and verify

on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Build Project with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint
        run: ./gradlew clean ktlintCheck

      - name: Tests
        run: ./gradlew :shared:testReleaseUnitTest

      - name: Build Project
        run: ./gradlew build

      - name: Build F-droid version
        run: |
          sh strip_google_services.sh
          ./gradlew build
